# Generated by Django 2.2.1 on 2019-08-29 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('minimum_players', models.IntegerField()),
                ('maximum_players', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('add_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ludomanagerapp.Game')),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ludomanagerapp.GameSession')),
                ('players', models.ManyToManyField(blank=True, null=True, to='ludomanagerapp.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_out', models.DateField()),
                ('expected_date_in', models.DateField()),
                ('date_in', models.DateField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ludomanagerapp.Game')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ludomanagerapp.Member')),
            ],
        ),
    ]
