# Generated by Django 2.2.1 on 2019-08-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludomanagerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinstance',
            name='players',
            field=models.ManyToManyField(blank=True, to='ludomanagerapp.Member'),
        ),
    ]
